
import { Route, Routes } from 'react-router-dom';
import './App.css';  
import Signin from './Components/Signin';
import MovieList from './Components/MovieList';
import Booking from './Components/Booking';
import Account from './Components/Account';
import Seat from './Components/Seat'; 

export let screensData=[
  {
      id:1,
      time:"9.00 AM",    
      seats:[
          {
              name:"A1",
              Booked:false, 
          },
          {
              name:"A2",
              Booked:false, 
          },
          {
              name:"A3",
              Booked:false, 
          },
          {
              name:"A4",
              Booked:false, 
          },
          {
              name:"A5",
              Booked:false, 
          },
          {
              name:"A6",
              Booked:false, 
          },
          {
              name:"A7",
              Booked:false, 
          },
          {
              name:"A8",
              Booked:false, 
          },
          {
              name:"A9",
              Booked:false, 
          },
          {
              name:"A10",
              Booked:false, 
          },
          {
            name:"A1",
            Booked:false, 
        },
        {
            name:"A2",
            Booked:false, 
        },
        {
            name:"A3",
            Booked:false, 
        },
        {
            name:"A4",
            Booked:false, 
        },
        {
            name:"A5",
            Booked:false, 
        },
        {
            name:"A6",
            Booked:false, 
        },
        {
            name:"A7",
            Booked:false, 
        },
        {
            name:"A8",
            Booked:false, 
        },
        {
            name:"A9",
            Booked:false, 
        },
        {
            name:"A10",
            Booked:false, 
        },
      ]    
  },
  {
      id:2,
      time:"10.15 AM",    
      seats:[
          {
              name:"A1",
              Booked:false, 
          },
          {
              name:"A2",
              Booked:false, 
          },
          {
              name:"A3",
              Booked:false, 
          },
          {
              name:"A4",
              Booked:false, 
          },
          {
              name:"A5",
              Booked:false, 
          },
          {
              name:"A6",
              Booked:false, 
          },
          {
              name:"A7",
              Booked:false, 
          },
          {
              name:"A8",
              Booked:false, 
          },
          {
              name:"A9",
              Booked:false, 
          },
          {
              name:"A10",
              Booked:false, 
          },
          
      ]    
  },
  {
      id:3,
      time:"11.00 AM",    
      seats:[
          {
              name:"A1",
              Booked:false, 
          },
          {
              name:"A2",
              Booked:false, 
          },
          {
              name:"A3",
              Booked:false, 
          },
          {
              name:"A4",
              Booked:false, 
          },
          {
              name:"A5",
              Booked:false, 
          },
          {
              name:"A6",
              Booked:false, 
          },
          {
              name:"A7",
              Booked:false, 
          },
          {
              name:"A8",
              Booked:false, 
          },
          {
              name:"A9",
              Booked:false, 
          },
          {
              name:"A10",
              Booked:false, 
          },
          
      ]    
  },
  {
      id:4,
      time:"2.30 PM",    
      seats:[
          {
              name:"A1",
              Booked:false, 
          },
          {
              name:"A2",
              Booked:false, 
          },
          {
              name:"A3",
              Booked:false, 
          },
          {
              name:"A4",
              Booked:false, 
          },
          {
              name:"A5",
              Booked:false, 
          },
          {
              name:"A6",
              Booked:false, 
          },
          {
              name:"A7",
              Booked:false, 
          },
          {
              name:"A8",
              Booked:false, 
          },
          {
              name:"A9",
              Booked:false, 
          },
          {
              name:"A10",
              Booked:false, 
          },
          
      ]    
  },
  {
      id:5,
      time:"4.00 PM",    
      seats:[
          {
              name:"A1",
              Booked:false, 
          },
          {
              name:"A2",
              Booked:false, 
          },
          {
              name:"A3",
              Booked:false, 
          },
          {
              name:"A4",
              Booked:false, 
          },
          {
              name:"A5",
              Booked:false, 
          },
          {
              name:"A6",
              Booked:false, 
          },
          {
              name:"A7",
              Booked:false, 
          },
          {
              name:"A8",
              Booked:false, 
          },
          {
              name:"A9",
              Booked:false, 
          },
          {
              name:"A10",
              Booked:false, 
          },
          
      ]    
  },
  {
      id:6,
      time:"5.30 PM",    
      seats:[
          {
              name:"A1",
              Booked:false, 
          },
          {
              name:"A2",
              Booked:false, 
          },
          {
              name:"A3",
              Booked:false, 
          },
          {
              name:"A4",
              Booked:false, 
          },
          {
              name:"A5",
              Booked:false, 
          },
          {
              name:"A6",
              Booked:false, 
          },
          {
              name:"A7",
              Booked:false, 
          },
          {
              name:"A8",
              Booked:false, 
          },
          {
              name:"A9",
              Booked:false, 
          },
          {
              name:"A10",
              Booked:false, 
          },
          
      ]    
  },
  {
      id:7,
      time:"7.45 PM",    
      seats:[
          {
              name:"A1",
              Booked:false, 
          },
          {
              name:"A2",
              Booked:false, 
          },
          {
              name:"A3",
              Booked:false, 
          },
          {
              name:"A4",
              Booked:false, 
          },
          {
              name:"A5",
              Booked:false, 
          },
          {
              name:"A6",
              Booked:false, 
          },
          {
              name:"A7",
              Booked:false, 
          },
          {
              name:"A8",
              Booked:false, 
          },
          {
              name:"A9",
              Booked:false, 
          },
          {
              name:"A10",
              Booked:false, 
          },
          
      ]    
  },
  {
      id:8,
      time:"10.30 PM",    
      seats:[
          {
              name:"A1",
              Booked:false, 
          },
          {
              name:"A2",
              Booked:false, 
          },
          {
              name:"A3",
              Booked:false, 
          },
          {
              name:"A4",
              Booked:false, 
          },
          {
              name:"A5",
              Booked:false, 
          },
          {
              name:"A6",
              Booked:false, 
          },
          {
              name:"A7",
              Booked:false, 
          },
          {
              name:"A8",
              Booked:false, 
          },
          {
              name:"A9",
              Booked:false, 
          },
          {
              name:"A10",
              Booked:false, 
          },
          
      ]    
  },
  
] 

function App() {
 
  
  return (
    <div className="App">
      <Routes>
        <Route path="/login" element={<Signin/>} />
        <Route path="/movies" element={<MovieList/>} />
        <Route path="/timings" element={<Booking/>} />
        <Route path="/seats" element={<Seat />} /> 
        <Route path="/account" element={<Account/>} />

        <Route path="*" element={<Signin/>} />
      </Routes>
    </div>
  );
}

export default App;
